name: CI
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "BRANCH=$branch" >> $GITHUB_ENV
      - name: publish version
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          sh .github/script/pushevent.sh Release
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
          GIT_BRANCH_TAG: ${{ env.BRANCH }}
